name: 'URI Parser'
description: 'Parse a Uniform Resource Identifier string in your GitHub Actions. Compatible with RFC 3986'
inputs:
  uri:
    description: 'URI string to parse'
    required: true
outputs:
  # See URI Syntax <https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax>
  decodedUri:
    description: 'The decoded URI string. Equivalent to JavaScript decodeURI(uri)'
  scheme:
    description: 'Scheme component of the URI. Does not include the colon (:).'
  authority:
    description: 'Authority component of the URI.'
  username:
    description: 'Username component of the URI.'
  password:
    description: 'Password component of the URI.'
  host:
    description: 'Host component of the URI. Includes the port if specified.'
  hostname:
    description: 'Hostname component of the URI. Does not include the port.'
  port:
    description: 'Port component of the URI.'
  path:
    description: 'Path component of the URI. Does not include the leading slash (/).'
  decodedPath:
    description: 'Decoded Path component of the URI. Equivalent to JavaScript decodeURIComponent(path). Does not include the leading slash (/).'
  query:
    description: 'Query component of the URI. Does not include the question mark (?).'
  fragment:
    description: 'Fragment component of the URI. Does not include the hash (#).'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'link'
  color: purple
